import { Router, type IRouter } from "express";
import healthRouter from "./health";
import reportsRouter from "./reports";
import customersRouter from "./customers";
import productsRouter from "./products";
import ordersRouter from "./orders";
import invoicesRouter from "./invoices";
import arRouter from "./ar";
import importsRouter from "./imports";
import promotionsRouter from "./promotions";
import shippingPoliciesRouter from "./shipping-policies";
import searchRouter from "./search";
import supplyManagementRouter from "./supply-management";
import workspaceDocumentsRouter from "./workspace-documents";
import usersRouter from "./users";
import authRouter from "./auth";
import collaborationRouter from "./collaboration";
import opportunitiesRouter from "./opportunities";
import betaPersistenceRouter from "./beta-persistence";

const router: IRouter = Router();

router.use(authRouter);
router.use(healthRouter);
router.use(reportsRouter);
router.use(customersRouter);
router.use(productsRouter);
router.use(ordersRouter);
router.use(invoicesRouter);
router.use(arRouter);
router.use(importsRouter);
router.use(promotionsRouter);
router.use(shippingPoliciesRouter);
router.use(searchRouter);
router.use(supplyManagementRouter);
router.use(workspaceDocumentsRouter);
router.use(usersRouter);
router.use(collaborationRouter);
router.use(opportunitiesRouter);
router.use(betaPersistenceRouter);

export default router;
